package Extractor

import (
	"path/filepath"
	"strings"
)

// SuffixMetaMap 文件后缀 -> meta 标签（空格分隔的关键词）
var SuffixMetaMap = map[string]string{
	// ========== 文字类 ==========
	".txt":   "document text",
	".text":  "document text",
	".log":   "document log",
	".ini":   "config",
	".cfg":   "config",
	".conf":  "config",
	".md":    "markdown document",
	".doc":   "microsoft word document",
	".docx":  "microsoft word document",
	".wps":   "wps document",
	".odt":   "opendocument text",
	".rtf":   "rich text document",
	".epub":  "ebook",
	".mobi":  "ebook kindle",
	".azw3":  "ebook kindle",
	".pdf":   "pdf document",
	".fb2":   "fictionbook ebook",
	".tex":   "latex document",
	".html":  "html web",
	".htm":   "html web",
	".xml":   "xml data",
	".json":  "json data",
	".yaml":  "yaml config",
	".rst":   "restructuredtext document",
	".pages": "pages document",
	".abw":   "abiword document",
	".lrf":   "sony ebook",

	// ========== 代码类（编程语言） ==========
	".go":         "golang go",
	".py":         "python python3",
	".js":         "javascript nodejs",
	".ts":         "typescript",
	".java":       "java jvm",
	".c":          "c clang",
	".cpp":        "cpp cplusplus",
	".cc":         "cpp cplusplus",
	".cxx":        "cpp cplusplus",
	".h":          "c cpp header",
	".hpp":        "cpp header",
	".rs":         "rust cargo",
	".rb":         "ruby",
	".php":        "php",
	".swift":      "swift ios",
	".kt":         "kotlin",
	".scala":      "scala",
	".cs":         "csharp dotnet",
	".fs":         "fsharp",
	".pl":         "perl",
	".pm":         "perl module",
	".lua":        "lua",
	".r":          "r statistics",
	".m":          "matlab objective-c", // 注意：.m 既可以是 MATLAB 也可以是 Objective-C
	".mm":         "objective-cpp",
	".sql":        "sql database",
	".sh":         "shell bash",
	".bash":       "bash shell",
	".zsh":        "zsh shell",
	".ps1":        "powershell",
	".vba":        "vba office",
	".vbs":        "vbscript",
	".groovy":     "groovy",
	".dart":       "dart flutter",
	".erl":        "erlang",
	".ex":         "elixir",
	".exs":        "elixir script",
	".clj":        "clojure",
	".jl":         "julia",
	".hs":         "haskell",
	".ml":         "ocaml",
	".scm":        "scheme",
	".lisp":       "common-lisp",
	".vim":        "vim script",
	".tf":         "terraform hcl",
	".dockerfile": "docker",

	// ========== 图片类 ==========
	".jpg":  "image jpeg",
	".jpeg": "image jpeg",
	".png":  "image png",
	".gif":  "image gif animated",
	".bmp":  "image bitmap",
	".tiff": "image tiff",
	".tif":  "image tiff",
	".webp": "image webp",
	".svg":  "vector image svg",
	".ico":  "icon image",
	".cur":  "cursor image",
	".arw":  "raw image sony",
	".cr2":  "raw image canon",
	".cr3":  "raw image canon",
	".nef":  "raw image nikon",
	".dng":  "raw image adobe",
	".raf":  "raw image fujifilm",
	".orf":  "raw image olympus",
	".pef":  "raw image pentax",
	".rw2":  "raw image panasonic",
	".srw":  "raw image samsung",
	".heic": "image heif apple",
	".heif": "image heif",
	".jp2":  "image jpeg2000",
	".psd":  "photoshop image",
	".xcf":  "gimp image",

	// ========== 视频类 ==========
	".mp4":  "video mp4",
	".m4v":  "video apple",
	".avi":  "video avi",
	".mov":  "video quicktime",
	".wmv":  "video windows",
	".flv":  "video flash",
	".f4v":  "video flash",
	".mkv":  "video matroska",
	".webm": "video webm",
	".m2ts": "video bluray",
	".mxf":  "video mxf",
	".mpeg": "video mpeg",
	".mpg":  "video mpeg",
	".mpe":  "video mpeg",
	".m2v":  "video mpeg2",
	".mp2v": "video mpeg2",
	".mpv2": "video mpeg2",
	".3gp":  "video mobile 3gpp",
	".3g2":  "video mobile 3gpp2",
	".ogv":  "video ogg",
	".rm":   "video realmedia",
	".rmvb": "video realmedia",
	".vob":  "video dvd",
	".divx": "video divx",
	".xvid": "video xvid",
	".asf":  "video asf",
}

func GetMetaForFile(filename string) string {
	ext := strings.ToLower(filepath.Ext(filename))
	if meta, ok := SuffixMetaMap[ext]; ok {
		return meta
	}
	return ""
}
