name: Generate & Deploy Docs

on:
  push:
    branches: [ master ]        # 按需修改
  workflow_dispatch:          # 允许手动触发

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'  # 根据项目调整

      - name: Run doc2go
        uses: nickgronow/doc2go-action@v1
        with:
          path: ./docs             # 要生成文档的包路径
